### ISSUE TITLE
No way to enable HTTP2

### ISSUE THREAD

**Issue by vaibhav-sinha** [turbinelabs/rotor#13] opened 2018-06-06 07:16 UTC
For CDS, the returned clusters do not have http2_protocol_options set and there is no way through which we can set them either ([cds.go](https://github.com/turbinelabs/rotor/blob/434aef5ece6f2afb63751516cafef2746675fb6e/xds/adapter/cds.go#L97)). Hence upstreams which support http2 don't work. Since gRPC uses http2, doing cluster discovery using rotor does not work with gRPC services. 

Can we add another bool parameter to the Cluster struct called enableHttp2 ([cluster.go](https://github.com/turbinelabs/api/blob/782002aab5ffc92bda0081717dd6b93742221f5d/cluster.go#L44)) . Different plugins can have their own mechanisms of finding the value for the parameter. For example, for EC2 integration, the presence of an extra tag may tell whether HTTP2 needs to be enabled.

**Comment by 9len** [comment] 2018-06-06 16:06
Hi @vaibhav-sinha, thanks for the issue.

This is more or less a duplicate of #7, and will have the same unsatisfying answer; we'd like to avoiding encoding envoy cluster configuration into labeling, as we think it will lead get snarly pretty quickly. 

Instead we plan to offer a way of specifying (1) configuration for specific clusters and (2) default configuration for all clusters at rotor startup. 

In the meantime, your best bet would probably be to statically configure your clusters in your envoy configuration (or serve CDS from a separate service), and use rotor only for EDS.

We do plan to fully support HTTP2 in the Turbine Labs API, along with a range of other cluster configuration options, but configuration of these will remain a part of our paid product.

Thanks!

**Comment by 9len** [comment] 2018-06-06 16:09
See #14 for a description of what we plan to add.

**Comment by vaibhav-sinha** [comment] 2018-06-06 18:49
I think proposed features in [#14](https://github.com/turbinelabs/rotor/issues/14) would be sufficient for my use cases. Thanks.

**Comment by 9len** [comment] 2018-06-09 14:25
closing in favor of the #14. thanks for reporting, @vaibhav-sinha

**Closed as completed by 9len** 2018-06-09 14:25 UTC

**Comment by 9len** [comment] 2018-07-03 19:40
this landed in 7acd7cd08a3512d0424a6b742033abb5d50f295c, available in the [`0.18.0`](https://github.com/turbinelabs/rotor/commits/0.18.0) tag.
